spring.application.name=tbotit

spring.datasource.url=jdbc:mysql://localhost:3306/houses_got?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Floquinho@18
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.show-sql=false
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=DEBUG


